baseURL = 'https://lochy.space'
locale = 'en-us'
title = "Lochy's Portfolio"
theme = "hugo-theme-tokyo-terminal"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup.goldmark.renderer]
  unsafe = true

[params]
  prompt = "V2"

  [params.dashboard]
    enabled = true
    ascii_art = """
 █████   █████  ████████
░░███   ░░███  ███░░░░███
 ░███    ░███ ░░░    ░███
 ░███    ░███    ███████
 ░░███   ███    ███░░░░
  ░░░█████░    ███      █
    ░░███     ░██████████
     ░░░      ░░░░░░░░░░
"""
    ascii_color = "#1eb2db"
    title = "Im Lochy, an aspiring network engineer from Edith Cowan University, Perth"
    subtitle = "Want to learn more about what I do?"
    #hint = "Press the highlighted keys to navigate."

  [[params.social]]
    name = "github"
    url = "https://github.com"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    [menu.main.params]
      shortcut = "a"
      icon = "☞"
  [[menu.main]]
    identifier = "experience"
    name = "Experience"
    url = "/experience"
    [menu.main.params]
      shortcut = "e"
      icon = "☞"
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects"
    [menu.main.params]
      shortcut = "p"
      icon = "☞"




# OLD ASCII ART
old = '''
 █████          ███████      █████████  █████   █████ █████ █████    █████   █████  ████████
░░███         ███░░░░░███   ███░░░░░███░░███   ░░███ ░░███ ░░███    ░░███   ░░███  ███░░░░███
 ░███        ███     ░░███ ███     ░░░  ░███    ░███  ░░███ ███      ░███    ░███ ░░░    ░███
 ░███       ░███      ░███░███          ░███████████   ░░█████       ░███    ░███    ███████
 ░███       ░███      ░███░███          ░███░░░░░███    ░░███        ░░███   ███    ███░░░░
 ░███      █░░███     ███ ░░███     ███ ░███    ░███     ░███         ░░░█████░    ███      █
 ███████████ ░░░███████░   ░░█████████  █████   █████    █████          ░░███     ░██████████
░░░░░░░░░░░    ░░░░░░░      ░░░░░░░░░  ░░░░░   ░░░░░    ░░░░░            ░░░      ░░░░░░░░░░
'''